### ISSUE TITLE
Malformed Text in Opportunity Descriptions

### ISSUE THREAD

**Issue by Danlobaton** [makegov/tango-public#1] opened 2024-09-24 22:55 UTC
**Describe the bug**
The opportunities endpoint is returning badly encoded opportunity descriptions. The descriptions are missing new lines, special characters, and other formatting elements, making them difficult to read and potentially losing important information. This also makes it pretty hard for us to use opportunity data with customers.

**To Reproduce**
1. Make a GET request to the opportunities endpoint
2. Retrieve the description field from the response
3. Observe the badly encoded text in the description

**Expected behavior**
The description field should contain properly formatted text with preserved new lines, special characters, and other formatting elements that were present in the original opportunity description.

**Example**
Solicitation number: FA521524Q0016

Current output:
"Amendment 2 -�The purpose of this amendment is to extend the solicitation due date 25 September 2024 1:00PM HST, remove the minimum size from the extended description and to answer question provided on the requirement. Amendment 1- The purpose of this amendment is to change the required dimensions of the AWGs to: minimum 14.5�x16.5�x 24� (inches), maximum 24�x24�x 25�"

Expected output (approximate, actual formatting may vary):
"Amendment 2 - The purpose of this amendment is to extend the solicitation due date 25 September 2024 1:00PM HST, remove the minimum size from the extended description and to answer question provided on the requirement.

Amendment 1 - The purpose of this amendment is to change the required dimensions of the AWGs to: minimum 14.5" x 16.5" x 24" (inches), maximum 24" x 24" x 25""

**Additional context**
This is a blocking issue for us and high-pri.

**Comment by vdavez** [comment] 2024-09-25 16:22
@Danlobaton Thank you for the report. I'll look into this today!

**Comment by vdavez** [comment] 2024-09-25 16:45
Ok, confirmed the report and the source of the problem! Will put it at the top of the queue for resolution.

**Comment by Danlobaton** [comment] 2024-09-25 22:06
thank you Dave!

**Comment by Danlobaton** [comment] 2024-10-01 18:10
hey @vdavez ! Do you have an idea on when our team can expect this one?

**Comment by vdavez** [comment] 2024-10-04 10:11
@Danlobaton Mind Can you confirm whether this is now resolved on your end? I checked `/api/opportunities?search=FA521524Q0016` and it looks like the data is correct now. I haven't updated the data backwards (yet!) but going forward it should be right...

**Comment by Danlobaton** [comment] 2024-10-04 18:43
@vdavez I can confirm that new opportunities are fixed!!

**Comment by vdavez** [comment] 2024-10-04 18:45
Awesome. Closing the issue! Thanks @Danlobaton!

**Closed by vdavez** 2024-10-04 18:45 UTC
Labels: bug, priority:high, ready for review
